/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yOlEolh8rzK
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Pomodor() {
  return (
    <div className="flex flex-col items-center space-y-8">
      <div className="relative w-36 h-36 rounded-full border-4 border-gray-200 dark:border-gray-800">
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <div className="text-4xl font-bold">25:00</div>
          <div className="text-lg">Task Name</div>
        </div>
        <div className="absolute inset-0 transform -rotate-90 origin-center">
          <div className="w-full h-full rounded-full bg-gradient-to-b from-green-400 to-green-600" />
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4">
        <div className="space-y-2">
          <Label htmlFor="task">Task</Label>
          <Input id="task" placeholder="Enter your task" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="duration">Duration (minutes)</Label>
          <Input id="duration" placeholder="25" required type="number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="short-break">Short Break (minutes)</Label>
          <Input id="short-break" placeholder="5" required type="number" />
        </div>
      </div>
      <div className="space-y-2">
        <Label htmlFor="long-break">Long Break (minutes)</Label>
        <Input id="long-break" placeholder="15" required type="number" />
      </div>
      <Button type="submit">Start Timer</Button>
    </div>
  )
}
